# Generated by Django 5.2.7 on 2025-10-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="furnishing_details",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Комплектация (опис.)"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="has_dishwasher",
            field=models.BooleanField(default=False, verbose_name="Посудомойка"),
        ),
        migrations.AddField(
            model_name="property",
            name="has_refrigerator",
            field=models.BooleanField(default=False, verbose_name="Холодильник"),
        ),
        migrations.AddField(
            model_name="property",
            name="has_shower",
            field=models.BooleanField(default=False, verbose_name="Душ"),
        ),
    ]
