# Generated by Django 5.2.7 on 2025-10-07 17:59

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="image",
            field=models.ImageField(blank=True, null=True, storage=core.storage.YandexMediaStorage(), upload_to="photos/%Y/%m/%d"),
        ),
    ]
