# Generated by Django 5.2.7 on 2025-10-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_property_furnishing_details_property_has_dishwasher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="ceiling_height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Высота потолков, м",
            ),
        ),
    ]
