# Generated by Django 5.2.7 on 2025-10-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_property_ceiling_height"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="has_ramp",
            field=models.BooleanField(
                default=False,
                help_text="Наличие пандуса для коммерческого объекта",
                verbose_name="Пандус",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="parking_places",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Количество мест для коммерческих объявлений",
                null=True,
                verbose_name="Паркомест",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="power",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Для коммерческих объектов ЦИАН",
                null=True,
                verbose_name="Выделенная мощность, кВт",
            ),
        ),
    ]
