# Generated by Django 5.2.7 on 2025-10-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_property_has_ramp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="rooms",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Количество комнат"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="floor_number",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Этаж"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="kitchen_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Площадь кухни, м²",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="living_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Жилая площадь, м²",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="total_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Общая площадь, м²",
            ),
        ),
    ]
