# Generated by Django 5.2.7 on 2025-10-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_photo_schema_normalize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="sort",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
