# Generated by Django 5.2.7 on 2025-10-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_property_rooms_alter_property_floor_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="commercial_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("office", "Офис"),
                    ("retail", "Торговая"),
                    ("warehouse", "Склад"),
                    ("production", "Производство"),
                    ("free_purpose", "Свободное назначение"),
                ],
                max_length=20,
                null=True,
                verbose_name="Подтип коммерции",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="flat_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apartment", "Квартира"),
                    ("studio", "Студия"),
                    ("apartments", "Апартаменты"),
                    ("penthouse", "Пентхаус"),
                ],
                max_length=20,
                null=True,
                verbose_name="Подтип квартиры",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="house_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("house", "Жилой дом"),
                    ("dacha", "Дача"),
                    ("townhouse", "Таунхаус"),
                    ("cottage", "Коттедж"),
                ],
                max_length=20,
                null=True,
                verbose_name="Подтип дома",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="land_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("izh", "ИЖС"),
                    ("agriculture", "С/Х"),
                    ("garden", "СНТ/садовый участок"),
                ],
                max_length=20,
                null=True,
                verbose_name="Подтип земельного участка",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="room_type_ext",
            field=models.CharField(
                blank=True,
                choices=[
                    ("room", "Комната"),
                    ("share", "Доля комнаты/комната в квартире"),
                ],
                max_length=30,
                null=True,
                verbose_name="Подтип комнаты",
            ),
        ),
    ]
