# Generated by Django 5.2.7 on 2025-10-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_photo_sort"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="bedrooms_count",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Количество спален"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="gas_supply_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("main_on_plot", "Магистральный в доме или на участке"),
                    ("border", "По границе участка"),
                    ("gasholder", "Газгольдер"),
                    ("none", "Нет"),
                ],
                max_length=16,
                verbose_name="Газ",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="has_bathhouse",
            field=models.BooleanField(default=False, verbose_name="Баня"),
        ),
        migrations.AddField(
            model_name="property",
            name="has_electricity",
            field=models.BooleanField(default=False, verbose_name="Электричество"),
        ),
        migrations.AddField(
            model_name="property",
            name="has_garage",
            field=models.BooleanField(default=False, verbose_name="Гараж"),
        ),
        migrations.AddField(
            model_name="property",
            name="has_pool",
            field=models.BooleanField(default=False, verbose_name="Бассейн"),
        ),
        migrations.AddField(
            model_name="property",
            name="has_security",
            field=models.BooleanField(default=False, verbose_name="Охрана"),
        ),
        migrations.AddField(
            model_name="property",
            name="house_condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ready", "Можно жить"),
                    ("needs_repair", "Нужен ремонт"),
                    ("need_finish", "Нужно достроить"),
                    ("needs_capital_or_demolition", "Нужен капремонт или под снос"),
                ],
                max_length=32,
                verbose_name="Состояние дома",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="sewerage_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("central", "Центральная"),
                    ("septic", "Септик"),
                    ("cesspool", "Выгребная яма"),
                    ("none", "Нет"),
                ],
                max_length=12,
                verbose_name="Канализация",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="water_supply_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("central", "Центральное"),
                    ("borehole", "Скважина"),
                    ("well", "Колодец"),
                    ("none", "Нет"),
                ],
                max_length=12,
                verbose_name="Водоснабжение",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="wc_location",
            field=models.CharField(
                blank=True,
                choices=[("outside", "На улице"), ("inside", "В доме")],
                max_length=12,
                verbose_name="Санузел",
            ),
        ),
    ]
