# Generated by Django 5.2.7 on 2025-10-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_property_bedrooms_count_property_gas_supply_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="sale_type",
            field=models.CharField(
                blank=True,
                choices=[("free", "Свободная"), ("alternative", "Альтернативная")],
                max_length=12,
                verbose_name="Тип продажи",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="room_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("separate", "Изолированная"),
                    ("combined", "Смежная"),
                    ("both", "Смежно‑изолированная"),
                ],
                max_length=16,
                verbose_name="Тип комнат",
            ),
        ),
    ]
