# Generated by Django 5.2.7 on 2025-10-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_property_commercial_type_property_flat_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="export_to_cian",
            field=models.BooleanField(default=True, verbose_name="Экспорт в ЦИАН"),
        ),
        migrations.AddField(
            model_name="property",
            name="export_to_domclick",
            field=models.BooleanField(default=False, verbose_name="Экспорт в ДомКлик"),
        ),
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[("active", "Активен"), ("archived", "В архиве")],
                default="active",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
