# Generated by Django 5.2.7 on 2025-10-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_property_sale_type_alter_property_room_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="agent_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Комиссия агента",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="bargain_allowed",
            field=models.BooleanField(default=False, verbose_name="Торг уместен"),
        ),
        migrations.AddField(
            model_name="property",
            name="bargain_conditions",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Условия торга"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="bargain_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Цена по торгу",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="beds_count",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Спальных мест"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="building_has_garbage_chute",
            field=models.BooleanField(default=False, verbose_name="Мусоропровод"),
        ),
        migrations.AddField(
            model_name="property",
            name="building_parking",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Парковка (опис.)"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="building_series",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Серия дома (опц.)"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="client_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Комиссия клиента",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="deposit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Залог (Deposit)",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="lease_term_type",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Тип срока аренды"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="prepay_months",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Предоплата (мес.)"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="rooms_for_sale_count",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Комнат продаётся"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="utilities_terms",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Коммуналка (условия)"
            ),
        ),
    ]
