# Generated by Django 5.2.7 on 2025-10-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_property_export_to_cian_property_export_to_domclick_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flatRent", "Квартира (аренда)"),
                    ("bedRent", "Койко-место (аренда)"),
                    ("roomRent", "Комната (аренда)"),
                    ("houseRent", "Дом/дача (аренда)"),
                    ("cottageRent", "Коттедж (аренда)"),
                    ("townhouseRent", "Таунхаус (аренда)"),
                    ("houseShareRent", "Часть дома (аренда)"),
                    ("garageRent", "Гараж (аренда)"),
                    ("buildingRent", "Здание (аренда)"),
                    ("commercialLandRent", "Коммерческая земля (аренда)"),
                    ("officeRent", "Офис (аренда)"),
                    ("freeAppointmentObjectRent", "ПСН (аренда)"),
                    ("industryRent", "Производство (аренда)"),
                    ("warehouseRent", "Склад (аренда)"),
                    ("shoppingAreaRent", "Торговая площадь (аренда)"),
                    ("dailyHouseRent", "Посуточно дом/дача/коттедж"),
                    ("dailyFlatRent", "Посуточно квартира"),
                    ("dailyBedRent", "Посуточно койко-место"),
                    ("dailyRoomRent", "Посуточно комната"),
                    ("flatShareSale", "Доля в квартире (продажа)"),
                    ("flatSale", "Квартира (продажа)"),
                    ("newBuildingFlatSale", "Квартира в новостройке (продажа)"),
                    ("roomSale", "Комната (продажа)"),
                    ("houseSale", "Дом/дача (продажа)"),
                    ("cottageSale", "Коттедж (продажа)"),
                    ("townhouseSale", "Таунхаус (продажа)"),
                    ("landSale", "Участок (продажа)"),
                    ("houseShareSale", "Часть дома (продажа)"),
                    ("garageSale", "Гараж (продажа)"),
                    ("businessSale", "Готовый бизнес (продажа)"),
                    ("buildingSale", "Здание (продажа)"),
                    ("commercialLandSale", "Коммерческая земля (продажа)"),
                    ("officeSale", "Офис (продажа)"),
                    ("freeAppointmentObjectSale", "ПСН (продажа)"),
                    ("industrySale", "Производство (продажа)"),
                    ("warehouseSale", "Склад (продажа)"),
                    ("shoppingAreaSale", "Торговая площадь (продажа)"),
                ],
                default=None,
                max_length=64,
                null=True,
                verbose_name="Категория (ЦИАН)",
            ),
        ),
    ]
