# Generated by Django 5.2.7 on 2025-10-04 15:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_property_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="external_id",
            field=models.CharField(
                blank=True,
                default=core.models.gen_external_id,
                max_length=100,
                unique=True,
                verbose_name="Внешний ID",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="phone_country",
            field=models.CharField(
                blank=True, default="7", max_length=8, verbose_name="Код страны"
            ),
        ),
    ]
