# Generated by Django 5.2.7 on 2025-10-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_property_agent_fee_property_bargain_allowed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="has_drainage",
            field=models.BooleanField(default=False, verbose_name="Есть канализация"),
        ),
        migrations.AddField(
            model_name="property",
            name="has_gas",
            field=models.BooleanField(default=False, verbose_name="Есть газ"),
        ),
        migrations.AddField(
            model_name="property",
            name="has_water",
            field=models.BooleanField(default=False, verbose_name="Есть водоснабжение"),
        ),
    ]
