# Generated by Django 5.2.7 on 2025-10-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_property_has_drainage_property_has_gas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="room_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Площадь комнаты, м²",
            ),
        ),
    ]
