# Generated by Django 5.2.7 on 2026-09-27 17:46

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_property_room_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=core.storage.YandexMediaStorage(),
                upload_to="photos/%Y/%m/%d",
            ),
        ),
    ]
