# Generated by Django 5.2.7 on 2025-10-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rename_export_to_domklik"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="В архиве"),
        ),
        migrations.AddField(
            model_name="property",
            name="operation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sale", "Продажа"),
                    ("rent_long", "Аренда"),
                    ("rent_daily", "Посуточно"),
                ],
                max_length=20,
                null=True,
                verbose_name="Тип сделки",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="subtype",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Подтип"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("house", "Дом"),
                    ("flat", "Квартира"),
                    ("room", "Комната"),
                    ("commercial", "Коммерция"),
                    ("land", "Земля"),
                    ("garage", "Гараж"),
                ],
                max_length=20,
                null=True,
                verbose_name="Тип объекта",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="external_id",
            field=models.CharField(
                blank=True, max_length=100, unique=True, verbose_name="Внешний ID"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="heating_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("central", "Центральное"),
                    ("gas", "Газовое"),
                    ("electric", "Электро"),
                    ("solid", "Твёрдое топливо"),
                ],
                max_length=20,
                verbose_name="Отопление",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="land_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Площадь участка",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="land_area_unit",
            field=models.CharField(
                blank=True,
                choices=[("sotka", "Сотка"), ("sqm", "м²")],
                max_length=10,
                verbose_name="Единица участка",
            ),
        ),
    ]
