name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dev requirements
        run: |
          pip install -r requirements-dev.txt || true
          pip install pytest pytest-django || true

      - name: Django checks
        run: python manage.py check

      - name: Pending migrations check
        run: python manage.py makemigrations --check --dry-run --noinput

      - name: Show migrations (core)
        run: |
          echo "== showmigrations core =="
          python manage.py showmigrations core

      - name: Guard: only one migration in core/mig_current
        run: |
          echo "Ensuring only one migration (0001_initial.py) exists for core.mig_current..."
          set -e
          files=$(ls -1 core/mig_current | grep -E '^[0-9]{4}_.+\\.py$' || true)
          echo "$files"
          if [ -z "$files" ]; then
            count=0
          else
            count=$(echo "$files" | wc -l)
          fi
          if [ "$count" -ne 1 ]; then
            echo "Expected exactly 1 migration file in core/mig_current, found: $count"
            exit 1
          fi
          echo "$files" | grep -q '^0001_initial\\.py$' || (echo "0001_initial.py not found" && exit 1)

      - name: Migrate
        run: python manage.py migrate --noinput

      - name: Tests
        run: python -m pytest
