name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dev requirements
        run: |
          pip install -r requirements-dev.txt || true
          pip install pytest pytest-django || true

      - name: Django checks
        run: python manage.py check

      - name: Pending migrations check
        run: python manage.py makemigrations --check --dry-run --noinput

      - name: Migrate
        run: python manage.py migrate --noinput

      - name: Tests
        run: python -m pytest
