name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install deps
        run: |
          pip install -r requirements.txt
          [ -f requirements-dev.txt ] && pip install -r requirements-dev.txt || true

      - name: Sanity check imports
        run: |
          python -c "import django_filters; print('django_filters OK:', getattr(django_filters,'__version__','?'))"

      - name: Django checks
        run: python manage.py check

      - name: Pending migrations check
        run: python manage.py makemigrations --check --dry-run --noinput

      - name: Tests
        run: python manage.py test -q
